create or replace TABLE EDOCHAT.EDO_TEST.TRANSACTIONS (
	TRANSACTION_ID NUMBER(38,0) NOT NULL,
	ORDER_ID NUMBER(38,0),
	PRODUCT_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	PRICE NUMBER(10,2),
	primary key (TRANSACTION_ID),
	foreign key (ORDER_ID) references EDOCHAT.EDO_TEST.ORDER_DETAILS(ORDER_ID)
);